### ISSUE TITLE
Condition based search

### ISSUE THREAD

**Issue by Bujupah** [KaikyuLotus/dart-mongo-lite#1]
Is there a way to do a search based condition ?
Similar to this ?

```js
db.collection.find( { qty: { $gt: 4 } } )
```

**Comment by KaikyuLotus** [comment]
Hello,

Thank you for opening this issue!

With commit 20ae437 (version 0.2.0-beta.1 on pub) I've added support for this feature.
Example:
```dart
db['collection'].find(callback: (e) => e['qty'] > 4);
```
So basically you can specify any callback which decides if the element satisfies your search.
You can also still use filter argument and you can use both together, filter will be applied first though.

Let me know if this solves your issue and sorry for the big delay.

**Comment by Bujupah** [comment]
Thanks.
