### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by takshalimbashia** [KaikyuLotus/dart-mongo-lite#2]
I didnt understand what does your library do? 
Do i need a backend (actual API) if i use your library direct from flutter android application along with mongo atlas like is it local or through internet.

**Comment by KaikyuLotus** [comment]
Hello,

to use this library you don't need any API, you can use it directly both on Flutter and on Dart server using a local json file.
This library is a very basic "imitation" of MongoDB, it's useful for storing simple data.

I'll update the README with a clearer description.
Thank you.
